### ISSUE TITLE
Test Cases - Help Wanted!

### ISSUE THREAD

**Issue by wizard97** [wizard97/ArduinoRingBuffer#3]
Test cases are needed to validate changes to the library. Really want to merge the dev branch into master, but need to ensure there are no bugs.

Any commits that address this will be really appreciated! :)

**Comment by GitMoDu** [comment]
I have tried (and failed) to compile this library on [Arduino for STM32](https://github.com/rogerclarkmelbourne/Arduino_STM32).  I get lots of compilation errors of redefinitions. Since this is a dependecy for the ProcessScheduler, do you think it's better to make the RingBuffer compile, or try to bring the ProcessScheduler to use the CPP version of ring buffer (which compiles and runs on Arduino for STM32)?

**Comment by wizard97** [comment]
Yeah, this has been in the pipeline for a while. A while ago, there was some work on the 2.0 branch https://github.com/wizard97/ArduinoProcessScheduler/tree/2.0 to replace RingBuf with the CPP version. I do believe it has been completely replaced, however I have no clue if the branch even compiles and/or has been tested. You are welcome to use it at your own risk.
